### ISSUE TITLE
Soup FFA

### ISSUE THREAD

**Issue by CyanCreeperPlayz** [McpeBooster/KnockbackFFA-McpeBooster#10]
In Soup FFA when I am low like around 3 and a half hearts if someone hits me I get TP back to the non pvp area zone and then  from there on players can hit me and I will take no damage and tp back to the non pvp area.

**Comment by McpeBooster** [comment]
SoupFFA Errors goes here: http://github.com/McpeBooster/SoupFFA-McpeBooster/
