### ISSUE TITLE
Fehler

### ISSUE THREAD

**Issue by chaosfreak93** [McpeBooster/KnockbackFFA-McpeBooster#15]
16:01:23 CRITICAL > Unbehandelter Fehler beim Ausführen des Kommandos 'kbf join KnockbackFFA-1' in kbf: Argument 1 passed to pocketmine\item\enchantment\EnchantmentInstance::__construct() must be an instance of pocketmine\item\enchantment\Enchantment, null given, called in /home/game/plugins/KnockBackFFA-master/src/KnockBackFFA/KnockbackFFA.php on line 425
16:01:23 CRITICAL > TypeError: "Argument 1 passed to pocketmine\item\enchantment\EnchantmentInstance::__construct() must be an instance of pocketmine\item\enchantment\Enchantment, null given, called in /home/game/plugins/KnockBackFFA-master/src/KnockBackFFA/KnockbackFFA.php on line 425" (EXCEPTION) in "src/pocketmine/item/enchantment/EnchantmentInstance" at line 41
16:01:23 DEBUG > #0 plugins/KnockBackFFA-master/src/KnockBackFFA/KnockbackFFA(425): pocketmine\item\enchantment\EnchantmentInstance->__construct(NULL , integer 2)
16:01:23 DEBUG > #1 plugins/KnockBackFFA-master/src/KnockBackFFA/KnockbackFFA(348): KnockBackFFA\KnockbackFFA->giveKit(pocketmine\Player object)
16:01:23 DEBUG > #2 plugins/KnockBackFFA-master/src/KnockBackFFA/KnockbackFFA(469): KnockBackFFA\KnockbackFFA->ArenaJoin(pocketmine\Player object, string KnockbackFFA-1)
16:01:23 DEBUG > #3 src/pocketmine/command/PluginCommand(58): KnockBackFFA\KnockbackFFA->onCommand(pocketmine\Player object, pocketmine\command\PluginCommand object, string kbf, array Array())
16:01:23 DEBUG > #4 src/pocketmine/command/SimpleCommandMap(283): pocketmine\command\PluginCommand->execute(pocketmine\Player object, string kbf, array Array())
16:01:23 DEBUG > #5 src/pocketmine/Server(2032): pocketmine\command\SimpleCommandMap->dispatch(pocketmine\Player object, string kbf join KnockbackFFA-1)
16:01:23 DEBUG > #6 src/pocketmine/Player(2190): pocketmine\Server->dispatchCommand(pocketmine\Player object, string kbf join KnockbackFFA-1)
16:01:23 DEBUG > #7 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(234): pocketmine\Player->chat(string /kbf join KnockbackFFA-1)
16:01:23 DEBUG > #8 src/pocketmine/network/mcpe/protocol/CommandRequestPacket(54): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleCommandRequest(pocketmine\network\mcpe\protocol\CommandRequestPacket object)
16:01:23 DEBUG > #9 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(94): pocketmine\network\mcpe\protocol\CommandRequestPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
16:01:23 DEBUG > #10 src/pocketmine/network/mcpe/protocol/BatchPacket(117): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\CommandRequestPacket object)
16:01:23 DEBUG > #11 src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter(94): pocketmine\network\mcpe\protocol\BatchPacket->handle(pocketmine\network\mcpe\PlayerNetworkSessionAdapter object)
16:01:23 DEBUG > #12 src/pocketmine/Player(3102): pocketmine\network\mcpe\PlayerNetworkSessionAdapter->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
16:01:23 DEBUG > #13 src/pocketmine/network/mcpe/RakLibInterface(153): pocketmine\Player->handleDataPacket(pocketmine\network\mcpe\protocol\BatchPacket object)
16:01:23 DEBUG > #14 vendor/pocketmine/raklib/server/ServerHandler(98): pocketmine\network\mcpe\RakLibInterface->handleEncapsulated(string 91.48.91.104 39709, raklib\protocol\EncapsulatedPacket object, integer 0)
16:01:23 DEBUG > #15 src/pocketmine/network/mcpe/RakLibInterface(94): raklib\server\ServerHandler->handlePacket()
16:01:23 DEBUG > #16 src/pocketmine/network/Network(89): pocketmine\network\mcpe\RakLibInterface->process()
16:01:23 DEBUG > #17 src/pocketmine/Server(2519): pocketmine\network\Network->processInterfaces()
16:01:23 DEBUG > #18 src/pocketmine/Server(2279): pocketmine\Server->tick()
16:01:23 DEBUG > #19 src/pocketmine/Server(2194): pocketmine\Server->tickProcessor()
16:01:23 DEBUG > #20 src/pocketmine/Server(1787): pocketmine\Server->start()
16:01:23 DEBUG > #21 src/pocketmine/PocketMine(301): pocketmine\Server->__construct(BaseClassLoader object, pocketmine\utils\MainLogger object, string /home/game/, string /home/game/plugins/)

**Comment by Aromastoffe** [comment]
Du brauchst Vanilla Enchantments oder so

**Comment by McpeBooster** [comment]
Plugin is outdatet
