### ISSUE TITLE
Russian

### ISSUE THREAD

**Issue by BogdanMakarchuk** [McpeBooster/KnockbackFFA-McpeBooster#2]
#translated by Twertik(Богдан Макарчук)

#Игрок
player.join= Вы вошли на арену
player.kill= Вы убили игрока §6{player}§7!
player.death= Вы были убиты игроком §6{player}§7!
player.void= Вы упали в пустоту!
player.spawnprotection= §cPvP разрешено дальше спавна игроков
player.killstreak= §6{player} §7сделал серию убийств §8[§e{killstreak}§8]§7!

#Арена
arena.ingame= §cНа арене уже идет игра!

**Comment by McpeBooster** [comment]
thanks I will add this :D
