### ISSUE TITLE
Commands doesnt working

### ISSUE THREAD

**Issue by armagadon159753** [McpeBooster/KnockbackFFA-McpeBooster#8]
When i make /kbf join or quit  i have this message:
https://github.com/McpeBooster/KnockbackFFA-McpeBooster/blob/master/src/KnockbackFFA/KnockbackFFA.php#L466

**Comment by McpeBooster** [comment]
You must do /kbf join <arena>

**Comment by McpeBooster** [comment]
* /kbf join arena

**Comment by armagadon159753** [comment]
Argh sorry for m'y stupid mistake.
I got used to Soup FFA plugin ^~^

**Comment by armagadon159753** [comment]
Ooh forgot can you fix spawnprotect message spam when player have low life ( soupffa )

**Comment by McpeBooster** [comment]
Sorry I dont understand

**Comment by armagadon159753** [comment]
$player = 2♥
$killer = kill->$player

Sometimes when $player teleported  on safespawn.
$killer receives several Smawn ProtectMessages
